# -*- coding: utf-8 -*-
"""Data_cleaning_gate.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Wqh1Q2BblXZGCaHKsYzaqVL-oNjhVrsC

# Data Cleaning
"""

import pandas as pd
import numpy as np

df = pd.read_csv('/content/2018_p1.csv')
df.tail()

############ WORKING CODE AS WRITTEN ORIGNALLY BEFORE CLEANING #################
labels = df["Label"]
label_df = pd.DataFrame()
label_list = []

for row in range(1023):
    label = eval(labels[row])
    if 'objects' in label:
        object_ = label['objects']
        gate_count = 0
        gate_lines = []
        for obj in object_:
            obj = eval(str(obj))
            # print(obj)
            if (obj["title"] == 'Gate'):
                gate_count += 1
                gate_lines.append(obj["line"])
        
        if (gate_count == 0):
            label_list.append("No Gate")
        else:
            label_list.append(gate_lines)
    else:
        label_list.append("No Object")

df.tail()
print(len(df))

############### MY LOGIC ###################
x_1t = []
y_1t = []
x_2t = []
y_2t = []
x_3t = []
y_3t = []
x_4t = []
y_4t = []

labels = df["Label"]
lb = eval(labels[4])
# print(lb)
object_ = lb['objects']
# print(object_)

g_l = []
for obj1 in object_:
    if(obj1['title'] == 'Gate'):
       g_l.append(obj1["line"])
print(g_l)


ele_list = g_l[0]
# print(len(ele_list))


# if(len(ele_list) == 2):
#     x_1t.append(ele_list[0]['x'])
#     y_1t.append(ele_list[0]['y'])
#     x_2t.append(ele_list[1]['x'])
#     y_2t.append(ele_list[1]['y'])

#     x_3t.append(0)
#     y_4t.append(0)
    
#     x_3t.append(0)
#     y_4t.append(0)
    

# if(len(ele_list) == 4):
#     x_1t.append(ele_list[0]['x'])
#     y_1t.append(ele_list[0]['y'])
    
#     x_2t.append(ele_list[1]['x'])
#     y_2t.append(ele_list[1]['y'])
    
#     x_3t.append(ele_list[2]['x'])
#     y_3t.append(ele_list[2]['y'])

#     x_4t.append(ele_list[3]['x'])
#     y_4t.append(ele_list[3]['y'])

# print(x_1t)
# print(y_1t)
# print(x_2t)
# print(y_2t)
# print(x_3t)
# print(y_3t)
# print(x_4t)
# print(y_4t)

df = pd.read_csv('/content/2018_p1.csv')

############### MY LOGIC ###################
x_1t = []
y_1t = []
x_2t = []
y_2t = []
x_3t = []
y_3t = []
x_4t = []
y_4t = []

# Trying to Incorporate that 
labels = df["Label"]
label_df = pd.DataFrame()
label_list = []

for row in range(len(df)):
    label = eval(labels[row])
    if 'objects' in label:
        object_ = label['objects']
        gate_count = 0
        gate_lines = []
        for obj in object_:
            obj = eval(str(obj))
            # print(obj)
            if (obj["title"] == 'Gate'):
                gate_count += 1
                gate_lines.append(obj["line"])
        
        if (gate_count == 0):
            label_list.append("No Gate")
            x_1t.append(0)
            y_1t.append(0)
            x_2t.append(0)
            y_2t.append(0)
            x_3t.append(0)
            y_3t.append(0)
            x_4t.append(0)
            y_4t.append(0)

        # print(gate_lines)
        else:
            if(len(gate_lines) > 0):
                ele_list = gate_lines[0]
            # print(ele_list)

                if(len(ele_list) == 2):
                    x_1t.append(ele_list[0]['x'])
                    y_1t.append(ele_list[0]['y'])
                    x_2t.append(ele_list[1]['x'])
                    y_2t.append(ele_list[1]['y'])

                    x_3t.append(0)
                    y_3t.append(0)

                    x_4t.append(0)
                    y_4t.append(0)

                elif(len(ele_list) == 4):
                    x_1t.append(ele_list[0]['x'])
                    y_1t.append(ele_list[0]['y'])
                    
                    x_2t.append(ele_list[1]['x'])
                    y_2t.append(ele_list[1]['y'])
                    
                    x_3t.append(ele_list[2]['x'])
                    y_3t.append(ele_list[2]['y'])

                    x_4t.append(ele_list[3]['x'])
                    y_4t.append(ele_list[3]['y'])
                else:
                    x_1t.append(-1)
                    y_1t.append(-1)
                    x_2t.append(-1)
                    y_2t.append(-1)
                    x_3t.append(-1)
                    y_3t.append(-1)
                    x_4t.append(-1)
                    y_4t.append(-1)
                    # print(ele_list)
        # else:
        #     label_list.append(gate_lines)

    else:
        label_list.append("No Object")
        x_1t.append(-2)
        y_1t.append(-2)
        x_2t.append(-2)
        y_2t.append(-2)
        x_3t.append(-2)
        y_3t.append(-2)
        x_4t.append(-2)
        y_4t.append(-2)


# print(x_1t)
# print(y_1t)
# print(x_2t)
# print(y_2t)
# print(x_3t)
# print(y_3t)
# print(x_4t)
# print(y_4t)

print(len(x_1t))
print(len(y_1t))
print(len(x_2t))
print(len(y_2t))
print(len(x_3t))
print(len(y_3t))
print(len(x_4t))
print(len(y_4t))


df['x1'] = np.array(x_1t)
df['y1'] = np.array(y_1t)

df['x2'] = np.array(x_2t)
df['y2'] = np.array(y_2t)

df['x3'] = np.array(x_3t)
df['y3'] = np.array(y_3t)

df['x4'] = np.array(x_4t)
df['y4'] = np.array(y_4t)

######## Test Cases
# [[{'x': 333.714, 'y': 469.714}, 
# {'x': 331.429, 'y': 130.286}, {'x': 650.286, 'y': 149.714}, {'x': 633.143, 'y': 454.857}]]


# [[{'x': 733.779, 'y': 716.998}, {'x': 803.659, 'y': 39.89},
#   {'x': 1220.526, 'y': 184.468}, {'x': 1109.683, 'y': 704.95}]]

# [[{'x': 153.296, 'y': 341.899}, {'x': 127.821, 'y': 103.24}, {
#     'x': 341.006, 'y': 91.173}, {'x': 358.436, 'y': 311.061}]]

# Passing all these cases

df.head()

